### ISSUE TITLE
steam deck ui not working properly

### ISSUE THREAD

**Issue by pyoroe** [holoiso-eol/holoiso#312]
turning sessions on gives a black screen, turning it off, logging into gamescope session gives a black screen, then goes back to the log in screen about 5 seconds later, any help? i'm using an GEFORCE RTX 2070 SUPER GPU and an INTEL I7 9700K CPU. any help would be apreciated.

**Comment by pyoroe** [comment]
EDIT, managed to get into the steam deck ui, but when booting, it takes a couple of boots of the ui for it to get up properly, and its really slow too, and 9 times out of 10, it will just crash to a black screen and reboot the ui. no clue whats happening. i still need help fixing this. :)

**Comment by Supermetal3** [comment]
Same problem here

**Comment by ZombieBear** [comment]
Same deal here, get a black screen on gamescope, but the KDE desktop works fine. Haven't been able to get into a login prompt outside of console though

**Comment by Savillion** [comment]
Exactly same. Specs: ryzen 7 3700x + nvidia 1070ti.

**Comment by pyoroe** [comment]
maybe it might get fixed in an update?
![image](https://user-images.githubusercontent.com/73830999/176730291-81490a60-2fb9-422b-83b9-980b2c62089d.png)
i'm gonna try to install holoiso and install the nvidia util thing and i'l report back once i've tried.

**Comment by BearGamesStudio** [comment]
![image](https://user-images.githubusercontent.com/73830999/176729290-cf848afa-e147-444e-a5cd-d1c02db8fa6b.png)
perhaps?

**Comment by ZombieBear** [comment]
So installing the 32bit libs fixed sddm (the login page) for me but gamescope still crashes at a black screen

**Comment by pyoroe** [comment]
hey, dumb question, i know, but how do i install the libs? i dont know that much about linux lol

**Comment by ZombieBear** [comment]
From a console you would run the command "sudo pacman -S lib32-nvidia-utils"
If you can use the plasma desktop they have a console program named console, if not, press Ctrl+Alt+F2 repeatedly during startup but before the black screen cause gamescope will segfault and crash your system, and you should get a login prompt

**Comment by pyoroe** [comment]
black screen, wtill lagging without. i'm just gonna try chimeraos.

**Comment by pyoroe** [comment]
![image](https://user-images.githubusercontent.com/73830999/177002536-fce42101-40c4-4cd7-ae81-40e1904eea36.png)
OOH, UPDATE! LETS TRY IT!

**Comment by theVakhovskeIsTaken** [comment]
Not my issue. Ask NVIDIA.

**Comment by pyoroe** [comment]
come on, i cant just "ask nvidia", not everyone wants to use amd you know.

**Comment by ZombieBear** [comment]
The issue appears to be with the driver support, the 1080ti is a pascal architecture card, whereas the drivers only support the 10 series cards that are Maxwell, so there's nothing he can do about it. I'm working on getting the steamdeck UI running on the desktop version of the client and i got that to launch but further testing is needed, currently it goes black at random, but is still responsive and comes back when I move the mouse.I'm running updates on it to see if it helps

**Comment by ghost** [comment]
> come on, i cant just "ask nvidia", not everyone wants to use amd you know.

the reasoning has been explained time and time again. 

cope.

**Comment by ZombieBear** [comment]
On X11 you can launch the desktop version of Steam in Steamedeck mode, but games won't run, on Wayland you can get games to run but the Steamdeck UI never loads :P
