### ISSUE TITLE
Ayaneo Geek 1S sleep/hibernate won't turn off the screen. 

### ISSUE THREAD

**Issue by savierxu** [holoiso-eol/holoiso#826]
Hi, 

Installed latest HoloISO onto Ayaneo Geek 1S. The sleep/hibernation function wont turn off the screen (maybe just backlight?).

To reproduce the issue, just press the power button after installation. 

The system would "freeze", buttons, wifi, touch screen everything "sleeps", except the screen/backlight. It's like sleeping with eyes open lol. 

I was able to go proper hibernate under windows, so could be some thing simple to fix? 

regards,

**Comment by theVakhovskeIsTaken** [comment]
@savierxu have you updated to the latest build?
Such thing happens due to improper WLAN card shutdown (blame mediatek), and is fixed

**Comment by savierxu** [comment]
Yes I just downloaded the iso two days agon. I tried updated it on both stable and beta, same issue. This happened to Chimeraos too when I tried that before. 

Since the screen is "on" through out the process, i could see wifi icon turned off/on though. You still think its WLAN? or maybe there 's a process to properly setup suspend/sleep/hibernate on new system? (don't know how to).

**Comment by savierxu** [comment]
some update, i did a full system update in desktop mode, it fixed the sleep screen light issue. however the problem came back after a reboot. so i guess there must be a conf file setting i need to manully edit for it to be permanant?
